import { bytesToHex, decodeSensor, decodeStatus } from '../protocol/wearableProtocol'

export type BleState = 'disconnected' | 'scanning' | 'connecting' | 'connected' | 'reconnecting' | 'error'
export type BlePermission = 'granted' | 'prompt' | 'denied' | 'unknown'
export type BleDiagnostics = { secureContext: boolean; supported: boolean; available: boolean | null; permission: BlePermission; lastErrorName: string; errorMessage: string; failedOperation?: string }
export type DiscoveredCharacteristic = { serviceUuid: string; uuid: string; properties: string[]; readable: boolean; writable: boolean; notifiable: boolean }
export type DiscoveredService = { uuid: string; characteristics: DiscoveredCharacteristic[] }
export type BleCallbacks = { onState?: (state: BleState) => void; onPacket?: (characteristic: string, data: DataView) => void; onError?: (error: BleError) => void; onDiagnostics?: (diagnostics: BleDiagnostics) => void; onDiscovery?: (services: DiscoveredService[]) => void; onDevice?: (device: BluetoothDevice) => void; onSensor?: (sensor: ReturnType<typeof decodeSensor>, data: DataView) => void; onStatus?: (status: ReturnType<typeof decodeStatus>, data: DataView) => void }

export const WEARABLE_SERVICE_UUID = '0000fe40-cc7a-482a-984a-7f2ed5b3e58f'
export const WRITE_CHARACTERISTIC_UUID = '0000fe41-8e22-4541-9d4c-21edae82ed19'
export const SENSOR_DATA_UUID = '0000fe42-8e22-4541-9d4c-21edae82ed19'
export const DEVICE_STATUS_UUID = '0000fe43-8e22-4541-9d4c-21edae82ed19'

export class BleError extends Error { constructor(public override name: string, message: string, public operation = 'unknown') { super(message) } }
type BluetoothDeviceLike = BluetoothDevice & { gatt: BluetoothRemoteGATTServer | null }
const initialDiagnostics: BleDiagnostics = { secureContext: false, supported: false, available: null, permission: 'unknown', lastErrorName: '', errorMessage: '', failedOperation: '' }
const asBleError = (error: unknown, operation: string) => { const value = error as { name?: string; message?: string }; return new BleError(value?.name || 'Error', value?.message || String(error), operation) }
const propertyNames = (c: BluetoothRemoteGATTCharacteristic) => ['read', 'write', 'writeWithoutResponse', 'notify', 'indicate'].filter((name) => Boolean((c.properties as Record<string, boolean>)[name]))

export class BleManager {
  private device: BluetoothDeviceLike | null = null; private callbacks: BleCallbacks; private diagnostics = initialDiagnostics; private writeCharacteristic: BluetoothRemoteGATTCharacteristic | null = null
  constructor(callbacks: BleCallbacks = {}) { this.callbacks = callbacks; void this.refreshDiagnostics() }
  private publish(patch: Partial<BleDiagnostics>) { this.diagnostics = { ...this.diagnostics, ...patch }; this.callbacks.onDiagnostics?.(this.diagnostics) }
  async refreshDiagnostics() { const secureContext = typeof window !== 'undefined' && window.isSecureContext; const supported = typeof navigator !== 'undefined' && 'bluetooth' in navigator; let available: boolean | null = null; let permission: BlePermission = 'unknown'; if (supported) { try { available = await navigator.bluetooth.getAvailability() } catch {} if (navigator.permissions?.query) { try { permission = (await navigator.permissions.query({ name: 'bluetooth' as PermissionName })).state as BlePermission } catch {} } } this.publish({ secureContext, supported, available, permission }); return this.diagnostics }
  async scan() { const d = await this.refreshDiagnostics(); if (!d.secureContext) throw this.fail('SecurityError', 'Web Bluetooth requires a secure HTTPS context.', 'scan'); if (!d.supported) throw this.fail('TypeError', 'Web Bluetooth is not supported in this browser.', 'scan'); this.callbacks.onState?.('scanning'); try { const device = await navigator.bluetooth.requestDevice({ acceptAllDevices: true, optionalServices: [WEARABLE_SERVICE_UUID] }); this.device = device as BluetoothDeviceLike; this.callbacks.onDevice?.(device); this.publish({ permission: 'granted', lastErrorName: '', errorMessage: '', failedOperation: '' }); return this.device } catch (error) { const e = asBleError(error, 'scan'); this.callbacks.onState?.('disconnected'); this.publish({ permission: e.name === 'NotAllowedError' ? 'denied' : this.diagnostics.permission, lastErrorName: e.name, errorMessage: e.message, failedOperation: 'scan' }); this.callbacks.onError?.(e); throw e } }
  private fail(name: string, message: string, operation: string) { const e = new BleError(name, message, operation); this.publish({ lastErrorName: name, errorMessage: message, failedOperation: operation }); this.callbacks.onError?.(e); return e }
  async connect(device = this.device) { if (!device?.gatt) throw this.fail('InvalidStateError', 'No wearable selected.', 'connect'); this.device = device; this.callbacks.onState?.('connecting'); try { const server = await device.gatt.connect(); const services = await server.getPrimaryServices(); const discovered: DiscoveredService[] = []; this.writeCharacteristic = null; for (const service of services) { const chars = await service.getCharacteristics(); const items: DiscoveredCharacteristic[] = []; for (const c of chars) { const properties = propertyNames(c); const item = { serviceUuid: service.uuid, uuid: c.uuid, properties, readable: properties.includes('read'), writable: properties.includes('write') || properties.includes('writeWithoutResponse'), notifiable: properties.includes('notify') || properties.includes('indicate') }; items.push(item); if (c.uuid.toLowerCase() === WRITE_CHARACTERISTIC_UUID) this.writeCharacteristic = c; if (c.uuid.toLowerCase() === SENSOR_DATA_UUID || c.uuid.toLowerCase() === DEVICE_STATUS_UUID) { if (item.notifiable) await c.startNotifications(); c.addEventListener('characteristicvaluechanged', () => { const value = c.value; if (!value) return; this.callbacks.onPacket?.(c.uuid, value); try { if (c.uuid.toLowerCase() === SENSOR_DATA_UUID) this.callbacks.onSensor?.(decodeSensor(value), value); else this.callbacks.onStatus?.(decodeStatus(value), value) } catch (error) { const e = asBleError(error, 'decode notification'); this.publish({ lastErrorName: e.name, errorMessage: e.message, failedOperation: e.operation }); this.callbacks.onError?.(e) } }) } } discovered.push({ uuid: service.uuid, characteristics: items }) } this.callbacks.onDiscovery?.(discovered); device.addEventListener('gattserverdisconnected', () => this.callbacks.onState?.('disconnected')); this.callbacks.onState?.('connected'); return device } catch (error) { const e = asBleError(error, 'connect'); this.publish({ lastErrorName: e.name, errorMessage: e.message, failedOperation: 'connect' }); this.callbacks.onState?.('error'); this.callbacks.onError?.(e); throw e } }
  async reconnect() { this.callbacks.onState?.('reconnecting'); return this.connect() }
  disconnect() { this.device?.gatt?.disconnect(); this.writeCharacteristic = null; this.callbacks.onState?.('disconnected') }
  async writeHex(hex: string) { const normalized = hex.replace(/[\s:-]/g, ''); if (!normalized || !/^[0-9a-f]+$/i.test(normalized) || normalized.length % 2) throw this.fail('TypeError', 'Enter an even number of hexadecimal characters.', 'write'); if (!this.writeCharacteristic) throw this.fail('InvalidStateError', 'Discover a writable characteristic before sending data.', 'write'); const data = Uint8Array.from(normalized.match(/.{2}/g)!, (byte) => parseInt(byte, 16)); try { await this.writeCharacteristic.writeValue(data) } catch (error) { const e = asBleError(error, 'write'); this.callbacks.onError?.(e); throw e } return data }
  get diagnostics() { return this.diagnostics }
}
export { bytesToHex }
